name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  SERVER_USERNAME: ubuntu
  SERVER_IP: 3.79.247.6
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy image to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -e
            if [ ! -d "~/94_matrix" ]; then
              echo "Directory ~/94_matrix does not exist. Cloning repository..."
              git clone https://github.com/D1Y0RBEKORIFJONOV/94_matrix.git ~/94_matrix
            fi
            cd ~/94_matrix
            if [ ! -f "docker-compose.yaml" ]; then
              echo "docker-compose.yaml not found in $(pwd)"
              exit 1
            fi
            git pull origin main
            docker-compose down
            docker-compose build
            docker-compose up -d
          script_stop: true
          timeout: 200s
