name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  SERVER_USERNAME: ubuntu
  SERVER_IP: 3.79.247.6
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy image to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -e
            if [ ! -d "cicd/lesson_ci_cd" ]; then
              mkdir -p cicd/lesson_ci_cd
            fi
            cd cicd/lesson_ci_cd
            docker-compose down
            git pull origin main
            docker-compose build
            docker-compose up -d
          script_stop: true
          timeout: 200s
